### Добавление задачи, blocks - список id (номеров) задач, которе она блокирует

POST localhost/tasks/add
Content-Type: application/json
Access:

{
  "type": "TASK",
  "status": "TODO",
  "title": "f0001"
}

### Добавление задачи, blocks - список id (номеров) задач, которе она блокирует

POST localhost/tasks/add
Content-Type: application/json
Access:

{
  "type": "TASK",
  "status": "TODO",
  "title": "f0002"
}

### Добавление задачи, blocks - список id (номеров) задач, которе она блокирует

POST localhost/tasks/add
Content-Type: application/json
Access:

{
  "type": "TASK",
  "status": "TODO",
  "title": "f0003"
}

### Добавление задачи, blocks - список id (номеров) задач, которе она блокирует

POST localhost/tasks/add
Content-Type: application/json
Access:

{
  "type": "TASK",
  "status": "TODO",
  "title": "f0004",
  "blocks": [
    1,
    2
  ]
}

### Добавление задачи, blocks - список id (номеров) задач, которе она блокирует

POST localhost/tasks/add
Content-Type: application/json
Access:

{
  "type": "TASK",
  "status": "TODO",
  "title": "f0004",
  "blocks": [
    3
  ]
}

### Добавление задачи, blocks - список id (номеров) задач, которе она блокирует

POST localhost/tasks/add
Content-Type: application/json
Access:

{
  "type": "TASK",
  "status": "TODO",
  "title": "f0005"
}

### Добавление списка задач, которые блокируются. Параметр id - id (номер) задачи. Blocks - список номеров задач, которые будут блокироваться

PUT localhost/tasks/refactor/blocks/5
Content-Type: application/json
Access:

{
  "blocks": [
    1
  ]
}

### Изменение статуса и исполнителя задачи. Параметр task - номер задачи, exec - id исполнителя, status - статус задачи

PUT localhost/tasks/refactor/state?task=5&exec=developer&status=IN_PROGRESS
Access:

### Изменение данных задачи (тип, приоритет, название, описание)

PUT localhost/tasks/refactor/info/1
Content-Type: application/json
Access:

{
  "type": "BUG",
  "priority": "CRITICAL",
  "title": "b0001",
  "description": "descr"
}

### Удаление задачи по ее номеру. Только для менеджера

DELETE localhost/tasks/delete/4
Access:

### Получение списка всех задач. Параметр r - для случайной сортировки

GET localhost/tasks
Access:

### Поиск задач по параметрам (номер(n), название(h), описание(d), тип(t), статус(s), автор(author), исполнитель(exec)). Параметр r - для случайной сортировки

GET localhost/tasks/search?r=true&exec=developer
Access:

###